export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const AUTH_SIGN_UP = "AUTH_SIGN_UP";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_LINK_GOOGLE = "AUTH_LINK_GOOGLE";
export const AUTH_LINK_FACEBOOK = "AUTH_LINK_FACEBOOK";
export const AUTH_UNLINK_GOOGLE = "AUTH_UNLINK_GOOGLE";
export const AUTH_UNLINK_FACEBOOK = "AUTH_UNLINK_FACEBOOK";
export const AUTH_ERROR = "AUTH_ERROR";

////FOR SURE USING THESES
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
